#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server
# Accepts 4 parameters:
#   The path to the file to be transferred
#   The IP of the server we want to transfer the file to
#   The username scp connects with
#   The path to the SSH private key that scp uses

PATH=$1
SERVER=$2
USR_NAME=$3
SSH_KEY=$4

if [ $# -eq 4 ]; then
     scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$PATH" "$USR_NAME@$SERVER:~/"
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
