#!/usr/bin/env bash
# A script that manages "manage_my_process".

if [[ -z "$1" ]]
then
		echo "Usage: manage_my_process {start|stop|restart}";

else
	if [[ "$1" == "start" ]]
	then
		./manage_my_process & touch /var/run/my_process.pid
		echo "$!" >> /var/run/my_process.pid
		echo "manage_my_process started"

	elif [[ "$1" == stop ]]
	then
		echo "manage_my_process stopped"
		# kill "$(cat /var/run/my_process.pid)"
		pkill -15 manage_my_process
		# kill -15 "$(pgrep -f manage_my_process)"
		rm -f /var/run/my_process.pid

	elif [[ "$1" == restart ]]
	then
		# kill "$(cat /var/run/my_process.pid)"
		pkill -15 manage_my_process
		rm -f /var/run/my_process.pid
		./manage_my_process & touch /var/run/my_process.pid
		echo "$!" > /var/run/my_process.pid
		echo "manage_my_process restarted"

	else
		echo "Usage: manage_my_process {start|stop|restart}";
	fi
fi
