#!/usr/bin/env bash
# A Scripts that displays "To infinity and beyond" indefinitely with a sleep 2
# "I am invincible!!!" when receiving a SIGTERM signal.

function no_pkill()
{
	echo "I am invincible!!!"
}

trap no_pkill SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done