#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd. displaying only the
# username, user id, and home directory path for user.

file="/etc/passwd"
if test -f $file;
then
	while read -r line;
	do
		echo "$line" | cut -d ":" -f1,3,6
	done < $file
fi